//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINET.Test.MensajesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MensajesWS.IPrestamos")]
    public interface IPrestamos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/CrearPrestamo", ReplyAction="http://tempuri.org/IPrestamos/CrearPrestamoResponse")]
        BINET.Entities.Prestamo CrearPrestamo(int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/CrearPrestamo", ReplyAction="http://tempuri.org/IPrestamos/CrearPrestamoResponse")]
        System.Threading.Tasks.Task<BINET.Entities.Prestamo> CrearPrestamoAsync(int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ObtenerPrestamo", ReplyAction="http://tempuri.org/IPrestamos/ObtenerPrestamoResponse")]
        BINET.Entities.Prestamo ObtenerPrestamo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ObtenerPrestamo", ReplyAction="http://tempuri.org/IPrestamos/ObtenerPrestamoResponse")]
        System.Threading.Tasks.Task<BINET.Entities.Prestamo> ObtenerPrestamoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ModificarPrestamo", ReplyAction="http://tempuri.org/IPrestamos/ModificarPrestamoResponse")]
        BINET.Entities.Prestamo ModificarPrestamo(int codigo, int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ModificarPrestamo", ReplyAction="http://tempuri.org/IPrestamos/ModificarPrestamoResponse")]
        System.Threading.Tasks.Task<BINET.Entities.Prestamo> ModificarPrestamoAsync(int codigo, int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/EliminarPrestamo", ReplyAction="http://tempuri.org/IPrestamos/EliminarPrestamoResponse")]
        void EliminarPrestamo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/EliminarPrestamo", ReplyAction="http://tempuri.org/IPrestamos/EliminarPrestamoResponse")]
        System.Threading.Tasks.Task EliminarPrestamoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ListarPrestamos", ReplyAction="http://tempuri.org/IPrestamos/ListarPrestamosResponse")]
        BINET.Entities.Prestamo[] ListarPrestamos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamos/ListarPrestamos", ReplyAction="http://tempuri.org/IPrestamos/ListarPrestamosResponse")]
        System.Threading.Tasks.Task<BINET.Entities.Prestamo[]> ListarPrestamosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrestamosChannel : BINET.Test.MensajesWS.IPrestamos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamosClient : System.ServiceModel.ClientBase<BINET.Test.MensajesWS.IPrestamos>, BINET.Test.MensajesWS.IPrestamos {
        
        public PrestamosClient() {
        }
        
        public PrestamosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BINET.Entities.Prestamo CrearPrestamo(int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino) {
            return base.Channel.CrearPrestamo(tarjeta, cuentaorigen, moneda, monto, cuotas, tea, tcea, montoc, fechor, cliente, cuentadestino);
        }
        
        public System.Threading.Tasks.Task<BINET.Entities.Prestamo> CrearPrestamoAsync(int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino) {
            return base.Channel.CrearPrestamoAsync(tarjeta, cuentaorigen, moneda, monto, cuotas, tea, tcea, montoc, fechor, cliente, cuentadestino);
        }
        
        public BINET.Entities.Prestamo ObtenerPrestamo(int codigo) {
            return base.Channel.ObtenerPrestamo(codigo);
        }
        
        public System.Threading.Tasks.Task<BINET.Entities.Prestamo> ObtenerPrestamoAsync(int codigo) {
            return base.Channel.ObtenerPrestamoAsync(codigo);
        }
        
        public BINET.Entities.Prestamo ModificarPrestamo(int codigo, int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino) {
            return base.Channel.ModificarPrestamo(codigo, tarjeta, cuentaorigen, moneda, monto, cuotas, tea, tcea, montoc, fechor, cliente, cuentadestino);
        }
        
        public System.Threading.Tasks.Task<BINET.Entities.Prestamo> ModificarPrestamoAsync(int codigo, int tarjeta, int cuentaorigen, int moneda, double monto, int cuotas, double tea, double tcea, double montoc, System.DateTime fechor, int cliente, int cuentadestino) {
            return base.Channel.ModificarPrestamoAsync(codigo, tarjeta, cuentaorigen, moneda, monto, cuotas, tea, tcea, montoc, fechor, cliente, cuentadestino);
        }
        
        public void EliminarPrestamo(int codigo) {
            base.Channel.EliminarPrestamo(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarPrestamoAsync(int codigo) {
            return base.Channel.EliminarPrestamoAsync(codigo);
        }
        
        public BINET.Entities.Prestamo[] ListarPrestamos() {
            return base.Channel.ListarPrestamos();
        }
        
        public System.Threading.Tasks.Task<BINET.Entities.Prestamo[]> ListarPrestamosAsync() {
            return base.Channel.ListarPrestamosAsync();
        }
    }
}
