//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINET.Web.UI.WF.CampanaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CampanaWS.ICampanasService")]
    public interface ICampanasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampanasService/ConsultarCampana", ReplyAction="http://tempuri.org/ICampanasService/ConsultarCampanaResponse")]
        BINET.Entities.Campana ConsultarCampana(int cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampanasService/ConsultarCampana", ReplyAction="http://tempuri.org/ICampanasService/ConsultarCampanaResponse")]
        System.Threading.Tasks.Task<BINET.Entities.Campana> ConsultarCampanaAsync(int cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICampanasServiceChannel : BINET.Web.UI.WF.CampanaWS.ICampanasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampanasServiceClient : System.ServiceModel.ClientBase<BINET.Web.UI.WF.CampanaWS.ICampanasService>, BINET.Web.UI.WF.CampanaWS.ICampanasService {
        
        public CampanasServiceClient() {
        }
        
        public CampanasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampanasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampanasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampanasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BINET.Entities.Campana ConsultarCampana(int cliente) {
            return base.Channel.ConsultarCampana(cliente);
        }
        
        public System.Threading.Tasks.Task<BINET.Entities.Campana> ConsultarCampanaAsync(int cliente) {
            return base.Channel.ConsultarCampanaAsync(cliente);
        }
    }
}
